version: '3.8'

services:
  mariadb:
    image: mariadb:10.11.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product-manager
      MYSQL_USER: 123
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
