spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/product-manager
    username: 123
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  logging:
    level:
      org.springframework.security: DEBUG

